# Basic set up for gradle package manager
version: 2
updates:
  - package-ecosystem: "npm"
    directory:  "/rqms-api-general/angular/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-api-general"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-api-offline"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-api-online"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-api-plugins"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-app-general"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-app-offline"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-app-online"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-app-plugins"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-domain-offline"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-domain-online"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-domain-plugins"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-infra"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/rqms-runable"
    schedule:
      interval: "monthly"
